# Generated by Django 3.2.7 on 2021-10-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210930_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='coment_author')),
                ('comment_content', models.CharField(max_length=200, verbose_name='comment_content')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='comment_date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='article')),
            ],
        ),
    ]
