# Generated by Django 3.2.7 on 2021-10-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_comment_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
