# Generated by Django 3.2.7 on 2021-10-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='c_author')),
                ('comment_content', models.CharField(max_length=200, verbose_name='c_content')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='comment_date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='article')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
